<?php

/*
 * This file is part of BedrockProtocol.
 * Copyright (C) 2014-2022 PocketMine Team <https://github.com/pmmp/BedrockProtocol>
 *
 * BedrockProtocol is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */

declare(strict_types=1);

namespace pocketmine\network\mcpe\protocol\types;

enum DisconnectReason : int {
	case UNKNOWN = 0;
	case CANT_CONNECT_NO_INTERNET = 1;
	case NO_PERMISSIONS = 2;
	case UNRECOVERABLE_ERROR = 3;
	case THIRD_PARTY_BLOCKED = 4;
	case THIRD_PARTY_NO_INTERNET = 5;
	case THIRD_PARTY_BAD_IP = 6;
	case THIRD_PARTY_NO_SERVER_OR_SERVER_LOCKED = 7;
	case VERSION_MISMATCH = 8;
	case SKIN_ISSUE = 9;
	case INVITE_SESSION_NOT_FOUND = 10;
	case EDU_LEVEL_SETTINGS_MISSING = 11;
	case LOCAL_SERVER_NOT_FOUND = 12;
	case LEGACY_DISCONNECT = 13;
	case INTERNAL_USER_LEAVE_GAME_ATTEMPTED = 14;
	case PLATFORM_LOCKED_SKINS_ERROR = 15;
	case REALMS_WORLD_UNASSIGNED = 16;
	case REALMS_SERVER_CANT_CONNECT = 17;
	case REALMS_SERVER_HIDDEN = 18;
	case REALMS_SERVER_DISABLED_BETA = 19;
	case REALMS_SERVER_DISABLED = 20;
	case CROSS_PLATFORM_DISABLED = 21;
	case TESTONLY_CANT_CONNECT = 22;
	case SESSION_NOT_FOUND = 23;
	case DEPRECATED_CLIENT_SETTINGS_INCOMPATIBLE_WITH_SERVER = 24;
	case SERVER_FULL = 25;
	case INVALID_PLATFORM_SKIN = 26;
	case EDITION_VERSION_MISMATCH = 27;
	case EDITION_MISMATCH = 28;
	case LEVEL_NEWER_THAN_EXE_VERSION = 29;
	case INTERNAL_NO_FAIL_OCCURRED = 30;
	case BANNED_SKIN = 31;
	case TIMEOUT = 32;
	case SERVER_NOT_FOUND = 33;
	case OUTDATED_SERVER = 34;
	case OUTDATED_CLIENT = 35;
	case DEPRECATED_NO_PREMIUM_PLATFORM = 36;
	case MULTIPLAYER_DISABLED = 37;
	case NO_WIFI = 38;
	case DEPRECATED_WORLD_CORRUPTION = 39;
	case NO_REASON = 40;
	case DISCONNECTED = 41;
	case INVALID_PLAYER = 42;
	case LOGGED_IN_OTHER_LOCATION = 43;
	case SERVER_ID_CONFLICT = 44;
	case NOT_ALLOWED = 45;
	case NOT_AUTHENTICATED = 46;
	case INVALID_TENANT = 47;
	case UNKNOWN_PACKET = 48;
	case UNEXPECTED_PACKET = 49;
	case INVALID_COMMAND_REQUEST_PACKET = 50;
	case HOST_SUSPENDED = 51;
	case LOGIN_PACKET_NO_REQUEST = 52;
	case LOGIN_PACKET_NO_CERT = 53;
	case MISSING_CLIENT = 54;
	case KICKED = 55;
	case KICKED_FOR_EXPLOIT = 56;
	case KICKED_FOR_IDLE = 57;
	case RESOURCE_PACK_PROBLEM = 58;
	case INCOMPATIBLE_PACK = 59;
	case OUT_OF_STORAGE = 60;
	case INVALID_LEVEL = 61;
	case DEPRECATED_DISCONNECT_PACKET = 62;
	case BLOCK_MISMATCH = 63;
	case INVALID_HEIGHTS = 64;
	case INVALID_WIDTHS = 65;
	case DEPRECATED_CONNECTION_LOST = 66;
	case DEPRECATED_ZOMBIE_CONNECTION = 67;
	case SHUTDOWN = 68;
	case DEPRECATED_REASON_NOT_SET = 69;
	case LOADING_STATE_TIMEOUT = 70;
	case RESOURCE_PACK_LOADING_FAILED = 71;
	case SEARCHING_FOR_SESSION_LOADING_SCREEN_FAILED = 72;
	case NETHER_NET_PROTOCOL_VERSION = 73;
	case SUBSYSTEM_STATUS_ERROR = 74;
	case EMPTY_AUTH_FROM_DISCOVERY = 75;
	case EMPTY_URL_FROM_DISCOVERY = 76;
	case EXPIRED_AUTH_FROM_DISCOVERY = 77;
	case UNKNOWN_SIGNAL_SERVICE_SIGN_IN_FAILURE = 78;
	case XBL_JOIN_LOBBY_FAILURE = 79;
	case UNSPECIFIED_CLIENT_INSTANCE_DISCONNECTION = 80;
	case NETHER_NET_SESSION_NOT_FOUND = 81;
	case NETHER_NET_CREATE_PEER_CONNECTION = 82;
	case NETHER_NET_ICE = 83;
	case NETHER_NET_CONNECT_REQUEST = 84;
	case NETHER_NET_CONNECT_RESPONSE = 85;
	case NETHER_NET_NEGOTIATION_TIMEOUT = 86;
	case NETHER_NET_INACTIVITY_TIMEOUT = 87;
	case STALE_CONNECTION_BEING_REPLACED = 88;
	case DEPRECATED_REALMS_SESSION_NOT_FOUND = 89;
	case BAD_PACKET = 90;
	case NETHER_NET_FAILED_TO_CREATE_OFFER = 91;
	case NETHER_NET_FAILED_TO_CREATE_ANSWER = 92;
	case NETHER_NET_FAILED_TO_SET_LOCAL_DESCRIPTION = 93;
	case NETHER_NET_FAILED_TO_SET_REMOTE_DESCRIPTION = 94;
	case NETHER_NET_NEGOTIATION_TIMEOUT_WAITING_FOR_RESPONSE = 95;
	case NETHER_NET_NEGOTIATION_TIMEOUT_WAITING_FOR_ACCEPT = 96;
	case NETHER_NET_INCOMING_CONNECTION_IGNORED = 97;
	case NETHER_NET_SIGNALING_PARSING_FAILURE = 98;
	case NETHER_NET_SIGNALING_UNKNOWN_ERROR = 99;
	case NETHER_NET_SIGNALING_UNICAST_DELIVERY_FAILED = 100;
	case NETHER_NET_SIGNALING_BROADCAST_DELIVERY_FAILED = 101;
	case NETHER_NET_SIGNALING_GENERIC_DELIVERY_FAILED = 102;
	case EDITOR_MISMATCH_EDITOR_WORLD = 103;
	case EDITOR_MISMATCH_VANILLA_WORLD = 104;
	case WORLD_TRANSFER_NOT_PRIMARY_CLIENT = 105;
	case INTERNAL_REQUEST_SERVER_SHUTDOWN = 106;
	case CLIENT_GAME_SETUP_CANCELLED = 107;
	case CLIENT_GAME_SETUP_FAILED = 108;
	case DEPRECATED_NO_VENUE = 109;
	case NETHER_NET_SIGNALING_SIGNIN_FAILED = 110;
	case SESSION_ACCESS_DENIED = 111;
	case SERVICE_SIGNIN_ISSUE = 112;
	case NETHER_NET_NO_SIGNALING_CHANNEL = 113;
	case NETHER_NET_NOT_LOGGED_IN = 114;
	case NETHER_NET_CLIENT_SIGNALING_ERROR = 115;
	case SUB_CLIENT_LOGIN_DISABLED = 116;
	case DEEP_LINK_TRYING_TO_OPEN_DEMO_WORLD_WHILE_SIGNED_IN = 117;
	case ASYNC_JOIN_TASK_DENIED = 118;
	case REALMS_TIMELINE_REQUIRED = 119;
	case GUEST_WITHOUT_HOST = 120;
	case FAILED_TO_JOIN_EXPERIENCE = 121;
	case NETHER_NET_DATA_CHANNEL_CLOSED = 122;
	case DISCOVERY_ENVIRONMENT_MISMATCH = 123;
	case HOST_WITHOUT_KEYS = 124;
	case HOST_SIGNED_OUT = 125;
	case SCRIPT_WATCHDOG_EXCEPTION = 126;
	case SCRIPT_MEMORY_LIMIT_EXCEEDED = 127;
	case STORAGE_LOW_DURING_GAMEPLAY = 128;
	case STORAGE_FULL_DURING_GAMEPLAY = 129;
	case LEVEL_STORAGE_CORRUPTION = 130;
	case EDITION_MISMATCH_VANILLA_TO_EDU = 131;
	case EDITION_MISMATCH_EDU_TO_VANILLA = 132;
	case EDITION_MISMATCH_EDITOR_TO_VANILLA = 133;
	case EDITION_MISMATCH_VANILLA_TO_EDITOR = 134;
	case DENY_LISTED = 135;
	case NONCE_MISSING = 136;
	case NONCE_NOT_FOUND = 137;
	case NONCE_EXPIRED = 138;
	case NONCE_NOT_VALID = 139;
	case HOST_DISCONNECTED = 140;
	case EDITOR_JOIN_INTENT_POLICY_FAILURE = 141;
}
